# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 037159d8cde2647830a04827bcb794a09f2c125f1d95c374b764cf18359090a817cfc46a795f9caa7d59505dd9ea58a57a4fd69e6fcd52ed416b4e8be8494578

test:
  secret_key_base: 5c7015690ca57430dfdee037488250109531290987cf3b0ef5453fc918da5741ef412d7a0efa2615bd378567f972b3069c63d89342c013f22507dd8ddc5db3a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
